apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "bartweb.fullname" . }}-trigger-cronjob
  labels:
    {{- include "bartweb.labels" . | nindent 4 }}
spec:
  schedule: "*/5 * * * *"

  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: bartweb-trigger
              image: ghcr.io/uvarc/uvarc-unified-service-base:develop
              imagePullPolicy: Always
              command: ["/bin/bash", "/opt/local/non_root_user/uvarc_unified_service/bin/pull-newkey.sh"]
              volumeMounts:
                - name: ssh-key-volume
                  mountPath: "/etc/ssh-key"
              env:
                - name: REMOTE_SCRIPT
                  value: "/standard/vol190/zanglab/usercase/trigger.py"
                - name: USERID
                  value: "cz3d"
              resources:
                limits:
                  cpu: "0.5"
                  memory: 512Mi
                requests:
                  cpu: "0.5"
                  memory: 512Mi

          volumes:
            - name: ssh-key-volume
              secret:
                secretName: cz3d-ssh-key
                defaultMode: 0400

          restartPolicy: OnFailure

      ttlSecondsAfterFinished: 86400
