apiVersion: apps/v1
kind: Deployment
metadata:
  name: bartweb-app
  namespace: zanglab
  labels:
    app: bartweb-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: bartweb-app

  template:
    metadata:
      labels:
        app: bartweb-app

    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"

      containers:
        - name: bartweb
          image: ghcr.io/zang-lab/bartweb_frontend:prod-0.0.5
          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          volumeMounts:
            - name: usercase-volume
              mountPath: /BARTweb/usercase

            - name: ssh-key-volume
              mountPath: /etc/ssh-key
              readOnly: true

          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "1Gi"

      volumes:
        - name: usercase-volume
          persistentVolumeClaim:
            claimName: bartweb-usercase-pvc

        - name: ssh-key-volume
          secret:
            secretName: cz3d-ssh-key
            defaultMode: 0400