apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bartweb.fullname" . }}-app
  labels:
    {{- include "bartweb.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bartweb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bartweb.labels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: usercase-volume
              mountPath: /BARTweb/usercase
      volumes:
        {{- if .Values.usercase.usePVC }}
        - name: usercase-volume
          persistentVolumeClaim:
            claimName: {{ .Values.usercase.pvcName }}
        {{- else }}
        - name: usercase-volume
          hostPath:
            path: {{ .Values.usercase.hostPath }}
            type: DirectoryOrCreate
        {{- end }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}