apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bartweb-ingress
  namespace: zanglab
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"

spec:
  tls:
    - hosts:
        - bartweb.pods.uvarc.io
      secretName: bartweb-nginx-tls-ingress-secret

  rules:
    - host: bartweb.pods.uvarc.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bartweb
                port:
                  number: 5000