apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bartweb-usercase-pvc
  namespace: zanglab
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-cephfs-sc