name: mirror

on:
  # schedule:
  #   - cron: '* * * */4 *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-accord-service:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set the env
      id: set_env
      run: echo "BUILD_PROJ=BARTweb_frontend" >> $GITHUB_ENV
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]ghcr.io/uvarc/${{ env.BUILD_PROJ }}:$(echo ${GITHUB_REF##*/})"
      id: extract_branch
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_PAT }}
    - name: Build and push
      if: github.ref == 'refs/heads/master'
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile_debian_20240506_fixed
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ steps.extract_branch.outputs.branch }}
          ghcr.io/uvarc/${{ env.BUILD_PROJ }}:latest
    - name: Build and push
      if: github.ref != 'refs/heads/master'
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile_debian_20240506_fixed
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ steps.extract_branch.outputs.branch }}


