name: Docker Build CI

on:
  push:
    branches:
      - develop
      - main
    tags:
      - 'prod-*.*'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # GHCR requires lowercase
      - name: Set GHCR_REPO
        run: |
          echo "GHCR_REPO=ghcr.io/${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      # Extract prod tag
      - name: Extract prod tag
        if: startsWith(github.ref, 'refs/tags/prod-')
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          yq eval ".image.tag = \"${TAG_NAME}\"" -i kubernetes/prod/values.yaml

      # Login to GHCR
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build & push for dev/feature branches
      - name: Build & push (non-main)
        if: github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/prod-')
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.GHCR_REPO }}:${{ github.ref_name }}

      # Build & push for main branch
      - name: Build & push (main)
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.GHCR_REPO }}:main
            ${{ env.GHCR_REPO }}:latest

      # Build & push for prod tags
      - name: Build & push (prod tag)
        if: startsWith(github.ref, 'refs/tags/prod-')
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.GHCR_REPO }}:${{ env.TAG_NAME }}

      # Commit Helm values
      - name: Push Helm tag update
        if: startsWith(github.ref, 'refs/tags/prod-')
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[skip ci] Update Helm image tag to ${{ env.TAG_NAME }}"
          branch: main
          file_pattern: kubernetes/prod/values.yaml
          commit_user_name: GitHub Actions Bot
          commit_user_email: github@virginia.edu
